// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBPB0ELcCd1KbjLcqCUZBLJlDVDHqKO4RQ",
      authDomain: "ocr-mobile-6035f.firebaseapp.com",
      projectId: "ocr-mobile-6035f",
      storageBucket: "ocr-mobile-6035f.appspot.com",
      messagingSenderId: "772178293651",
      appId: "1:772178293651:web:1da04c89e3f94177c22e66",
      measurementId: "G-8Z34TF6L05");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD8GLi-Muna9NUpa10BOojP1UHFxGCE5IM",
    appId: "1:772178293651:android:949db87bcd722d70c22e66",
    messagingSenderId: "772178293651",
    projectId: "ocr-mobile-6035f",
    storageBucket: "ocr-mobile-6035f.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDLql97Qw3wW9HcY_yqxqcpKUCD0nzS0',
    appId: '1:772178293651:ios:538c929b9d3e8ee1c22e66',
    messagingSenderId: '772178293651',
    projectId: 'ocr-mobile-6035f',
    storageBucket: 'ocr-mobile-6035f.appspot.com',
    iosBundleId: 'com.example.tubesKel3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVDLql97Qw3wW9HcY_yqxqcpKUCD0nzS0',
    appId: '1:772178293651:ios:71dd2a890e1d6942c22e66',
    messagingSenderId: '772178293651',
    projectId: 'ocr-mobile-6035f',
    storageBucket: 'ocr-mobile-6035f.appspot.com',
    iosBundleId: 'com.example.tubesKel3.RunnerTests',
  );
}
